# Generated by Django 3.0.6 on 2020-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20200530_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
