# Generated by Django 3.0.6 on 2020-05-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20200530_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='photo_name',
        ),
    ]
