# Generated by Django 3.0.6 on 2020-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_remove_picture_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='face/'),
        ),
    ]
